services:
  web:
    build: .
    entrypoint: sh -c "poetry install --with dev --with test; DEBUG=1 exec ./manage.py runserver 0.0.0.0:8000"
    container_name: django_web
    environment:
      - DATABASE_URL=postgis://realbustimes:realbustimes@db:5432/realbustimes
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - TURNSTILE_SITEKEY
      - TURNSTILE_SECRET
      - DISABLE_REGISTRATION
      - NEW_VEHICLE_WEBHOOK_URL
      - TFL_VEHICLE_WEBHOOK_URL
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - REDIS_URL=redis://redis:6379
      - NTA_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PYTHONWARNINGS=all
    volumes:
      - .:/app
    ports:
      - "8077:8000"
      - "35729:35729"
    restart: on-failure
    depends_on:
      - db
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.django_web.rule=Host(`ukbuses.org`)
      - traefik.http.routers.django_web.entrypoints=websecure
      - traefik.http.routers.django_web.tls.certresolver=letsencrypt
      - traefik.http.services.django_web.loadbalancer.server.port=8000

  db:
    image: postgis/postgis:17-3.4
    container_name: realbustimes_db
    restart: unless-stopped
    shm_size: "10g"
    environment:
      POSTGRES_DB: realbustimes
      POSTGRES_USER: realbustimes
      POSTGRES_PASSWORD: realbustimes
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    mem_limit: 12288m
    command: [
      "redis-server",
      "--maxmemory", "11gb",
      "--maxmemory-policy", "allkeys-lru"
    ]

volumes:
  db_data:
