services:

  web:
    build: .
    entrypoint: sh -c "poetry install --with dev --with test && exec ./manage.py runserver 0.0.0.0:8000"
    container_name: django_web
    environment:
      - DATABASE_URL
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - TURNSTILE_SITEKEY
      - TURNSTILE_SECRET
      - DISABLE_REGISTRATION
      - NEW_VEHICLE_WEBHOOK_URL
      - TFL_VEHICLE_WEBHOOK_URL
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
      - NTA_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PYTHONWARNINGS=all
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    restart: unless-stopped

  db:
    image: postgis/postgis:17-3.4
    container_name: realbustimes_db
    restart: unless-stopped
    shm_size: "10g"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: always
    mem_limit: 12288m
    command: [
      "redis-server",
      "--maxmemory", "11gb",
      "--maxmemory-policy", "allkeys-lru"
    ]

volumes:
  db_data:
  static_volume:
