services:
  web:
    build: .
    entrypoint: sh -c "poetry install --with dev --with test; DEBUG=1 exec ./manage.py runserver 0.0.0.0:8000"
    container_name: django_web
    env_file: ".env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "35729:35729"
    restart: on-failure
    depends_on:
      - db
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.django_web.rule=Host(`ukbuses.org`)
      - traefik.http.routers.django_web.entrypoints=websecure
      - traefik.http.routers.django_web.tls.certresolver=letsencrypt
      - traefik.http.services.django_web.loadbalancer.server.port=8000

  db:
    image: postgis/postgis:17-3.4
    container_name: realbustimes_db
    restart: unless-stopped
    shm_size: "10g"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    mem_limit: 12288m
    command: [
      "redis-server",
      "--maxmemory", "11gb",
      "--maxmemory-policy", "allkeys-lru"
    ]

volumes:
  db_data:
