wget -O EA.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/EA.zip
wget -O EM.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/EM.zip
wget -O L.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/L.zip
wget -O NE.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/NE.zip
wget -O NW.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/NW.zip
wget -O S.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/S.zip
wget -O SE.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/SE.zip
wget -O SW.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/SW.zip
wget -O W.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/W.zip
wget -O WM.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/WM.zip
wget -O Y.zip ftp://kai%40mybustimes.cc:Kdn8%2C82FT%23Y%7DUVi@ftp.tnds.basemap.co.uk/Y.zip