[program:bod_avl]
directory=/srv/realbustimes/realbustimes
command=/srv/realbustimes/.local/bin/poetry run ./manage.py import_bod_avl
user=realbustimes
autorestart=true

[program:listen]
directory=/srv/realbustimes/realbustimes
command=/srv/realbustimes/.local/bin/poetry run ./manage.py listen
user=realbustimes
autorestart=true
