# Generated by Django 5.1.7 on 2025-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_sirisource_operators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='line_name_override',
            field=models.CharField(blank=True, help_text='Override the line name for this service on the route pages only', max_length=64),
        ),
    ]
