# Generated by Django 5.1.7 on 2025-08-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_service_line_name_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecolour',
            name='background',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
